# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:  
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)'
    Contents: '**'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'client'
    customCommand: 'install --save-dev  --unsafe-perm node-sass'
- task: Npm@1
  inputs:
    workingDir: 'client'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'client'
    customCommand: 'run build'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'client/dist/client'
    Contents: '**'
    TargetFolder: '$(Build.BinariesDirectory)/app/wwwroot'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: server/SmartHome.API/SmartHome.API.csproj
    arguments: '-o $(Build.BinariesDirectory)/app -c Release -f netcoreapp2.2'
    zipAfterPublish: false
    modifyOutputPath: false
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'ef migrations script -i -o "$(Build.ArtifactStagingDirectory)/migrations.sql"'
    workingDirectory: 'server/SmartHome.Data'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/app'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'artifact'
    publishLocation: 'Container'
